### ISSUE TITLE
Background JavaScript animation not working

### ISSUE THREAD

**Issue by iahmed5** [punctuations/juststop#8]
**Screenshots**
![image](https://user-images.githubusercontent.com/56458394/77809877-a0461780-7089-11ea-8f7d-9b8db337d9ac.png)

**Desktop:**
 - Windows
 - Chrome

**Comment by punctuations** [comment]
Please specify which Javascript animations

**Comment by iahmed5** [comment]
> Please specify which Javascript animations

![image](https://user-images.githubusercontent.com/56458394/77811960-0afd5000-7096-11ea-9d42-31e132636c70.png)

particles animation in the background

**Comment by punctuations** [comment]
those only appear during certain dates
`if (d.getMonth() == new Date('Dec 03, 2020 00:00:00').getMonth()) {
	  $( "span.snowflake" ).show();
	} else {
	  $( "span.snowflake" ).hide();
	}					`

**Comment by punctuations** [comment]
if you want to chat more about this issue you can reach me here: https://discord.gg/SK53UMK
